steps:

- name: 'gcr.io/cloud-builders/docker'
  dir: 'example0-minimal'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/example0-minimal', '.' ]
  
images:
- 'gcr.io/$PROJECT_ID/example0-minimal:$COMMIT_SHA'