apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example5-config-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: example5-config-service
    spec:
      containers:
      - name: example5-config-service
        image: 'gcr.io/gcp-meetup-akl/example5-config-service'
        imagePullPolicy: Always
