apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example5-module1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: example5-module1
    spec:
      containers:
      - name: example5-module1
        image: 'gcr.io/gcp-meetup-akl/example5-module1'
        imagePullPolicy: Always
