apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example1-basics
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: example1-basics
    spec:
      containers:
      - name: example1-basics
        image: '{{ .Values.docker.registry }}/example1-basics'
        imagePullPolicy: Always
